{
 "title": "Airgap Kubernetes Cluster Monitoring (Community 17483)",
 "description": "Monitors Kubernetes (1.16 and above) cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [
  "airgap",
  "cadvisor",
  "community",
  "grafana-17483",
  "kubernetes"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Network I/O pressure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[1m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Total usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster CPU usage (1m avg)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster filesystem usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/(sd[a-z][0-9]+|vd[a-z][0-9]+|xvd[a-z][0-9]+|nvme[0-9]+n[0-9]+p?[0-9]*)$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/(sd[a-z][0-9]+|vd[a-z][0-9]+|xvd[a-z][0-9]+|nvme[0-9]+n[0-9]+p?[0-9]*)$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/(sd[a-z][0-9]+|vd[a-z][0-9]+|xvd[a-z][0-9]+|nvme[0-9]+n[0-9]+p?[0-9]*)$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/(sd[a-z][0-9]+|vd[a-z][0-9]+|xvd[a-z][0-9]+|nvme[0-9]+n[0-9]+p?[0-9]*)$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Pods CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Pods CPU usage (1m avg)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\".*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "System services CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "System services CPU usage (1m avg)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{systemd_service_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (systemd_service_name)",
       "legendFormat": "{{ systemd_service_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Containers CPU usage (1m avg)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (container_name, pod)",
       "legendFormat": "pod: {{ pod }} | {{ container_name }}"
      },
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname, name, image)",
       "legendFormat": "docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname, rkt_container_name)",
       "legendFormat": "rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "All processes CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "All processes CPU usage (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\".*\",kubernetes_io_hostname=~\"^$Node$\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "System services memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "System services memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{systemd_service_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}) by (systemd_service_name)",
     "legendFormat": "{{ systemd_service_name }}"
    }
   ]
  },
  {
   "title": "Containers memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Containers memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_name, pod)",
     "legendFormat": "pod: {{ pod }} | {{ container_name }}"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}) by (kubernetes_io_hostname, name, image)",
     "legendFormat": "docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}) by (kubernetes_io_hostname, rkt_container_name)",
     "legendFormat": "rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
    }
   ]
  },
  {
   "title": "All processes memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "All processes memory usage",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) by (id)",
       "legendFormat": "{{ id }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pods network I/O (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (pod)",
     "legendFormat": "-> {{ pod }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (pod)",
     "legendFormat": "<- {{ pod }}"
    }
   ]
  },
  {
   "title": "Containers network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Containers network I/O (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (container_name, pod)",
     "legendFormat": "-> pod: {{ pod }} | {{ container_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (container_name, pod)",
     "legendFormat": "<- pod: {{ pod }} | {{ container_name }}"
    },
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname, name, image)",
     "legendFormat": "-> docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname, name, image)",
     "legendFormat": "<- docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname, rkt_container_name)",
     "legendFormat": "-> rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname, rkt_container_name)",
     "legendFormat": "<- rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
    }
   ]
  },
  {
   "title": "All processes network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {}
   ]
  },
  {
   "title": "All processes network I/O (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (id)",
     "legendFormat": "-> {{ id }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (id)",
     "legendFormat": "<- {{ id }}"
    }
   ]
  }
 ]
}