{
 "title": "Airgap Kube-State-Metrics Overview (Community 25091)",
 "description": "kube-state-metrics-overview dashboard",
 "tags": [
  "airgap",
  "community",
  "grafana-25091",
  "kube-state-metrics",
  "kubernetes"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ready Nodes",
     "type": "stat",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"})"
      }
     ]
    },
    {
     "title": "CPU Requests by Namespace",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
     "targets": [
      {
       "expr": "sum by (namespace) (kube_pod_container_resource_requests{resource=\"cpu\",unit=\"core\", namespace=~\"${Namespace:regex}\"})",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Memory Requests by Namespace",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
     "targets": [
      {
       "expr": "sum by (namespace) (kube_pod_container_resource_requests{resource=\"memory\",unit=\"byte\", namespace=~\"${Namespace:regex}\"})",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Total Pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=~\"${Namespace:regex}\"})"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\", namespace=~\"${Namespace:regex}\"})"
    }
   ]
  },
  {
   "title": "Pending Pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\", namespace=~\"${Namespace:regex}\"})"
    }
   ]
  },
  {
   "title": "Error Pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Failed\", namespace=~\"${Namespace:regex}\"})"
    }
   ]
  },
  {
   "title": "Pods by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count by (namespace) (kube_pod_info{namespace=~\"${Namespace:regex}\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Container Restarts by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (namespace) (\r\n    increase(kube_pod_container_status_restarts_total{namespace=~\"${Namespace:regex}\"} [$__interval])\r\n)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Failed Pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{phase=\"Failed\", namespace=~\"${Namespace:regex}\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods List ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "max by(namespace, pod, node) (kube_pod_info{namespace=~\"${Namespace:regex}\"})",
     "legendFormat": "{{configmap}}"
    }
   ]
  },
  { "title": "Deployments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Total Available Deployments",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=~\"${Namespace:regex}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployment Replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum by (namespace, deployment) (kube_deployment_status_replicas{namespace=~\"${Namespace:regex}\"})",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Deployment Status Replicas Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum by (namespace, deployment) (kube_deployment_status_replicas_available{namespace=~\"${Namespace:regex}\"})",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Deployment Status Replicas Unavailable",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum by (namespace, deployment) (kube_deployment_status_replicas_unavailable{namespace=~\"${Namespace:regex}\"})",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  { "title": "StatefulSets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Total Available StatefulSet",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_statefulset_status_replicas_ready{namespace=~\"${Namespace:regex}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "StatefulSet Replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum by (namespace, deployment) (kube_statefulset_status_replicas{namespace=~\"${Namespace:regex}\"})",
     "legendFormat": "{{statefulset}}"
    }
   ]
  },
  {
   "title": "StatefulSet Replicas Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum by (namespace, deployment) (kube_statefulset_status_replicas_available{namespace=~\"${Namespace:regex}\"})",
     "legendFormat": "{{statefulset}}"
    }
   ]
  },
  {
   "title": "StatefulSet Replicas Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "sum by (namespace, deployment) (kube_statefulset_status_replicas_available{namespace=~\"${Namespace:regex}\"})",
     "legendFormat": "{{statefulset}}"
    }
   ]
  },
  { "title": "DeamonSets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Available DaemonSet Desired",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace, daemonset) (kube_daemonset_status_desired_number_scheduled{namespace=~\"${Namespace:regex}\"})",
     "legendFormat": "{{daemonset}}"
    }
   ]
  },
  {
   "title": "DaemonSet Replicas Ready",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace, daemonset) (kube_daemonset_status_number_ready{namespace=~\"${Namespace:regex}\"})",
     "legendFormat": "{{daemonset}}"
    }
   ]
  },
  { "title": "Config Maps and Secrets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Number of Config Maps",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_configmap_info{namespace=~\"${Namespace:regex}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Config Maps List ",
   "type": "table",
   "gridPos": { "h": 12, "w": 10, "x": 4, "y": 68 },
   "targets": [
    {
     "expr": "max by(namespace, configmap, job) (kube_configmap_info{namespace=~\"${Namespace:regex}\"})",
     "legendFormat": "{{configmap}}"
    }
   ]
  },
  {
   "title": "Secrets List",
   "type": "table",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 68 },
   "targets": [
    {
     "expr": "max by(namespace, secret, job) (kube_secret_info{namespace=~\"${Namespace:regex}\"})",
     "legendFormat": "{{secret}}"
    }
   ]
  },
  {
   "title": "Number of Secrets",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_secret_info{namespace=~\"${Namespace:regex}\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}